"""Add PaymentRecord and individual seat tracking

Revision ID: 60d899a898d3
Revises: dbd85e35233f
Create Date: 2026-03-31 22:50:23.847737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d899a898d3'
down_revision: Union[str, None] = 'dbd85e35233f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gocardless_payment_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_entity_id'), 'payment_records', ['entity_id'], unique=False)
    op.add_column('subscription_seats', sa.Column('status', sa.Enum('trial', 'active', 'past_due', 'cancelled', name='subscriptionstatus'), nullable=False))
    op.add_column('subscription_seats', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscription_seats', sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscription_seats', sa.Column('gocardless_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_seats', 'gocardless_subscription_id')
    op.drop_column('subscription_seats', 'next_billing_date')
    op.drop_column('subscription_seats', 'trial_ends_at')
    op.drop_column('subscription_seats', 'status')
    op.drop_index(op.f('ix_payment_records_entity_id'), table_name='payment_records')
    op.drop_table('payment_records')
    # ### end Alembic commands ###
