"""add revisit_interval_days and notifications

Revision ID: cb0aa3013fb7
Revises: f3cd87e5eb8f
Create Date: 2026-03-29 21:51:44.252830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add revisit_interval_days and notifications

Revision ID: cb0aa3013fb7
Revises: f3cd87e5eb8f
Create Date: 2026-03-29 21:51:44.252830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0aa3013fb7'
down_revision: Union[str, None] = 'f3cd87e5eb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('revisit_interval_days', sa.Integer(), nullable=True))
    op.execute("UPDATE organization_settings SET revisit_interval_days = 8")
    op.alter_column('organization_settings', 'revisit_interval_days', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'revisit_interval_days')
    # ### end Alembic commands ###
