"""Add GoCardless subscription fields

Revision ID: dbd85e35233f
Revises: cb0aa3013fb7
Create Date: 2026-03-31 22:16:59.578325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd85e35233f'
down_revision: Union[str, None] = 'cb0aa3013fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('gocardless_subscription_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('gocardless_mandate_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('gocardless_customer_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('gocardless_redirect_flow_id', sa.String(), nullable=True))
    op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'gocardless_redirect_flow_id')
    op.drop_column('subscriptions', 'gocardless_customer_id')
    op.drop_column('subscriptions', 'gocardless_mandate_id')
    op.drop_column('subscriptions', 'gocardless_subscription_id')
    # ### end Alembic commands ###
