"""add_is_email_verified_to_users

Revision ID: f3cd87e5eb8f
Revises: bee02f714eb2
Create Date: 2026-03-08 20:14:21.807182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cd87e5eb8f'
down_revision: Union[str, None] = 'bee02f714eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_org_owner', 'organizations', 'users', ['owner_id'], ['id'], use_alter=True)
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_constraint('fk_org_owner', 'organizations', type_='foreignkey')
    # ### end Alembic commands ###
